trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: salesforce-variable-group

steps:
  - task: DownloadSecureFile@1
    name: serverKey
    inputs:
      secureFile: 'server.key'

  - script: |
      npm install @salesforce/cli --global
    displayName: 'Install Salesforce CLI'

  - script: |
      sf org login jwt \
        --client-id $(sf-clientid-qa) \
        --jwt-key-file $(serverKey.secureFilePath) \
        --username $(sf-username-qa) \
        --instance-url https://login.salesforce.com \
        --set-default
    displayName: 'Authenticate to Salesforce'

  - script: |
      sf project deploy start \
        --source-dir force-app \
        --target-org $(sf-username-qa)
    displayName: 'Deploy to Salesforce Org'

  - script: |
      sf apex run test \
        --target-org $(sf-username-qa) \
        --result-format human \
        --wait 10
    displayName: 'Run Apex Tests'